version: '3.8'

services:
  web:
    image: nginx
    volumes:
      - web-data:/usr/share/nginx/html
    networks:
      - appnet

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  cache:
    image: redis
    networks:
      - appnet

volumes:
  db-data:
  web-data:

networks:
  appnet:
