Vagrant.configure("2") do |config|

  # VM1: Загальнодоступний вебсервер
  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "bento/ubuntu-24.04"
    webserver.vm.network "public_network"
    webserver.vm.synced_folder ".", "/vagrant"
    webserver.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
    SHELL
  end

  # VM2: Приватний сервер
  config.vm.define "private_server" do |private_server|
    private_server.vm.box = "bento/ubuntu-24.04"
    private_server.vm.network "private_network", ip: "192.168.50.4"
    private_server.vm.synced_folder ".", "/vagrant"
    private_server.vm.provision "shell", path: "provision.sh"
  end

  # VM3: Загальнодоступний сервер зі статичним IP
  config.vm.define "public_static_ip" do |public_static_ip|
    public_static_ip.vm.box = "bento/ubuntu-24.04"
    public_static_ip.vm.network "public_network", bridge: "wlan0", ip: "192.168.1.100"
    public_static_ip.vm.synced_folder ".", "/vagrant_public"
    public_static_ip.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx
    SHELL
  end

end
